# Generated by Django 4.0.3 on 2022-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_average', models.DecimalField(decimal_places=4, max_digits=100)),
                ('updated', models.BooleanField(null=True)),
            ],
        ),
    ]
